---
- name: Configure EtherChannel
  hosts: routers
  tasks:
    - name: Configure EtherChannel on interfaces
      ios_config:
        lines:
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - channel-group 1 mode on
        parents: interface range Ethernet1/0-1

    - name: Assign IP to Port-Channel
      ios_config:
        lines:
          - ip address 192.168.10.1 255.255.255.0
          - no shutdown
        parents: interface Port-channel1