---
- name: Configure VTP
  hosts: switches
  tasks:
    - name: Configure VTP domain and mode
      ios_config:
        lines:
          - vtp domain abc.com
          - vtp mode server
          - vtp password 123

    - name: Create VLANs
      ios_config:
        lines:
          - vlan 10
          - vlan 20
        when: inventory_hostname == 'R1'